version: "3"

services:
  bot:
    build:
      context: "."
    volumes:
      - "./:/root/bukibot"
    ports:
      - "$WEBAPP_PORT:8000"
    command: python bot.py
    environment:
      MYSQL_DATABASE: "bukibot"
      MYSQL_USER: "bukibot"
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    volumes:
      - ./mysql-storage:/var/lib/mysql
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: "bukibot"
      MYSQL_USER: "bukibot"
      MYSQL_PASSWORD: $MYSQL_PASSWORD

