# Generated by Django 3.2.14 on 2022-07-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=50, verbose_name='サーバーID')),
                ('server_name', models.CharField(max_length=200, verbose_name='サーバー名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splatoon2_textchat_id', models.CharField(max_length=50, verbose_name='Splatoon2用テキストチャット')),
                ('splatoon3_textchat_id', models.CharField(max_length=50, verbose_name='Splatoon3用テキストチャット')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='app.server', verbose_name='サーバー設定')),
            ],
        ),
    ]
