# Generated by Django 4.0.6 on 2022-08-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='app.server', verbose_name='サーバー'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='splatoon2_textchat_id',
            field=models.CharField(max_length=50, verbose_name='Splatoon2用テキストチャットID'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='splatoon3_textchat_id',
            field=models.CharField(max_length=50, verbose_name='Splatoon3用テキストチャットID'),
        ),
        migrations.CreateModel(
            name='RouletteVoiceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voicechat_id', models.CharField(help_text='ルーレットを有効化するボイスチャットのID', max_length=50, verbose_name='ボイスチャットID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_voicechat', to='app.server', verbose_name='サーバー')),
            ],
        ),
    ]
