# Generated by Django 4.0.6 on 2022-08-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_serverconfig_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettevoicechat',
            name='voicechat_name',
            field=models.CharField(default='dummy', max_length=200, verbose_name='ボイスチャット名'),
            preserve_default=False,
        ),
    ]
