site_name: ブキルーレット
nav:
    - 使い方: index.md
    - about: about.md
    - 更新履歴: changeLog.md
# theme: readthedocs
theme: material
site_author: murufon
markdown_extensions:
    - nl2br
    - markdown_newtab
