site_name: むる太郎
nav:
    - むる太郎とは: index.md
    - コマンド: command.md
    - about: about.md
    - 更新履歴: changeLog.md
# theme: readthedocs
theme: material
site_author: murufon
markdown_extensions:
    - nl2br
